package com.main.citas.enums;

public enum Especialidades {
    MEDICINA_GENERAL,
    CARDIOLOGIA,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    GERIATRIA,
    NEUROLOGIA,
    PEDIATRIA,
    PSIQUIATRIA,
    TRAUMATOLOGIA
}
